Repository HAND-PYEON/handpyeon-web, pull requests merged in 2023-07, with the labels that each got.

#21 style(web): HotTrend 상세페이지
  apps/web/public/icons/crown.svg
  apps/web/src/app/hottrend/[category]/[rank]/HotTrendInfo.tsx
  apps/web/src/app/hottrend/[category]/[rank]/HotTrendRankList.tsx
  apps/web/src/app/hottrend/[category]/[rank]/page.tsx
  apps/web/src/app/hottrend/[category]/layout.tsx
  apps/web/src/app/hottrend/layout.tsx
  apps/web/src/app/main/[category]/EventItems.tsx
  apps/web/src/app/not-found.tsx
  apps/web/src/assets/chevronRight.svg
  apps/web/src/components/HotTrendItem/index.tsx
  apps/web/src/components/RankBox/index.tsx
  apps/web/src/components/TabBar/OneBar.tsx
  apps/web/src/components/TabBar/index.tsx
  apps/web/src/components/TabCategory/OneCategory.tsx
  apps/web/src/components/icons/ChevronRightIcon.tsx
  apps/web/src/components/icons/CrownIcon.tsx
  apps/web/src/dummy/hotTrend.ts
  apps/web/tailwind.config.js
Labels: feature, style

#22 style(web): 검색 페이지 메인
  apps/web/public/icons/icon-search-black.svg
  apps/web/public/icons/icon-search-white.svg
  apps/web/public/icons/x-circle.svg
  apps/web/src/app/event/[category]/detail/[id]/page.tsx
  apps/web/src/app/event/[category]/page.tsx
  apps/web/src/app/hottrend/layout.tsx
  apps/web/src/app/main/Header.tsx
  apps/web/src/app/search/components/HotTrendSection.tsx
  apps/web/src/app/search/components/PerfectMatchSection.tsx
  apps/web/src/app/search/components/PerfectMatchSlides.tsx
  apps/web/src/app/search/page.tsx
  apps/web/src/components/BasicHeader/index.tsx
  apps/web/src/components/BasicLayout/index.tsx
  apps/web/src/components/HomeIconButton/index.tsx
  apps/web/src/components/SearchHeader/index.tsx
  apps/web/src/components/SearchIconButton/index.tsx
  apps/web/src/components/SearchInput/index.tsx
  apps/web/src/components/icons/XcircleIcon.tsx
  apps/web/src/hooks/useGoHome.ts
Labels: feature, style

#25 feat(web): 검색 결과 페이지
  apps/web/public/icons/handpyeon-text.svg
  apps/web/src/app/event/[category]/components/EventItemSection.tsx
  apps/web/src/app/search/SearchRenderer.tsx
  apps/web/src/app/search/components/HotTrendSection.tsx
  apps/web/src/app/search/components/PerfectMatchSection.tsx
  apps/web/src/app/search/page.tsx
  apps/web/src/app/search/view/SearchResultView.tsx
  apps/web/src/app/search/view/SearchView.tsx
  apps/web/src/components/BasicLayout/index.tsx
  apps/web/src/components/SearchHeader/index.tsx
  apps/web/src/components/SearchInput/index.tsx
  apps/web/src/components/SearchLayout/index.tsx
  apps/web/src/components/icons/HandpyeonTextIcon.tsx
  packages/ui/dist/index.d.ts
Labels: feature, style

#28 feat(web): 서버 api 연동을 위한 템플릿 작업
  apps/web/next.config.js
  apps/web/package.json
  apps/web/src/apis/promotion.ts
  apps/web/src/apis/type.ts
  apps/web/src/app/appProviders.tsx
  apps/web/src/app/event/[category]/components/EventItemSection.tsx
  apps/web/src/app/event/[category]/detail/[id]/components/EventItemDetailCard.tsx
  apps/web/src/app/event/[category]/detail/[id]/components/EventItemDetailSection.tsx
  apps/web/src/app/event/[category]/detail/[id]/components/EventItemTotalSection.tsx
  apps/web/src/app/event/[category]/detail/[id]/page.tsx
  apps/web/src/app/event/[category]/page.tsx
  apps/web/src/app/getQueryClient.tsx
  apps/web/src/app/hottrend/[category]/layout.tsx
  apps/web/src/app/layout.tsx
  apps/web/src/app/main/CategoryChildren.tsx
  apps/web/src/app/main/[category]/EventItems.tsx
  apps/web/src/app/main/[category]/HotTrend.tsx
  apps/web/src/app/main/[category]/page.tsx
  apps/web/src/app/main/page.tsx
  apps/web/src/app/not-found.tsx
  apps/web/src/app/page.tsx
  apps/web/src/app/search/view/SearchResultView.tsx
  apps/web/src/app/type.ts
  apps/web/src/components/ApiErrorBoundary.tsx
  apps/web/src/components/EventItemCard/index.tsx
  apps/web/src/components/GlobalErrorBoundary.tsx
  apps/web/src/constants/conveniences.ts
  apps/web/src/dummy/hotTrend.ts
  apps/web/src/hooks/query/usePromotion.ts
  apps/web/src/http/client.ts
  apps/web/src/lib/error.ts
  apps/web/src/store/tabBar.ts
  yarn.lock
Labels: feature

#29 feat(web): 데스크톱 뷰 포트 스타일 작업
  apps/web/public/image/LeftArrow.png
  apps/web/public/image/RightArrow.png
  apps/web/public/image/brand-contents.png
  apps/web/public/image/handpyeon-text.png
  apps/web/public/image/intro-contents.png
  apps/web/src/app/layout.tsx
  apps/web/src/app/main/CategoryChildren.tsx
  apps/web/src/app/main/layout.tsx
Labels: style

#34 feat(web): 추천 콘텐츠 API 연동
  apps/web/src/apis/recommendation.ts
  apps/web/src/apis/type.ts
  apps/web/src/app/recommendation/[category]/components/ContentItem.tsx
  apps/web/src/app/recommendation/[category]/page.tsx
  apps/web/src/app/recommendation/[category]/pages/HoneyPage.tsx
  apps/web/src/app/recommendation/[category]/pages/NowPage.tsx
  apps/web/src/app/recommendation/[category]/pages/SituationPage.tsx
  apps/web/src/app/recommendation/contents/[id]/page.tsx
  apps/web/src/hooks/query/useRecommendation.ts
  apps/web/src/utils/extractValues.ts
  apps/web/src/utils/index.ts
Labels: feature

#36 feat(web): 추천 콘텐츠 배너 API 업데이트
  apps/web/src/apis/recommendation.ts
  apps/web/src/apis/type.ts
Labels: feature

#37 feat(web): 핫트렌드 API 업데이트 (리스트, 디테일)
  apps/web/src/apis/hotTrend.ts
  apps/web/src/apis/type.ts
  apps/web/src/app/hottrend/[category]/[id]/HotTrendInfo.tsx
  apps/web/src/app/hottrend/[category]/[id]/HotTrendRankList.tsx
  apps/web/src/app/hottrend/[category]/[id]/page.tsx
  apps/web/src/app/hottrend/[category]/[rank]/page.tsx
  apps/web/src/app/hottrend/[category]/layout.tsx
  apps/web/src/app/hottrend/[category]/route.ts
  apps/web/src/app/not-found.tsx
  apps/web/src/app/recommendation/contents/[id]/page.tsx
  apps/web/src/components/HotTrendItem/index.tsx
  apps/web/src/hooks/query/useHotTrends.ts
Labels: feature

#38 feat(web) : 추천 콘텐츠 API 적용 업데이트
  apps/web/src/apis/recommendation.ts
  apps/web/src/apis/type.ts
  apps/web/src/app/recommendation/[category]/components/ContentItem.tsx
  apps/web/src/app/recommendation/contents/[id]/ContentsDetailCard.tsx
  apps/web/src/app/recommendation/contents/[id]/page.tsx
  apps/web/src/constants/conveniences.ts
Labels: feature

#35 feat(web): 행사상품 리스트 api 연결
  apps/web/next.config.js
  apps/web/package.json
  apps/web/src/apis/promotion.ts
  apps/web/src/apis/type.ts
  apps/web/src/app/event/[category]/components/EventItemSection.tsx
  apps/web/src/app/event/[category]/components/EventItems.tsx
  apps/web/src/app/event/[category]/detail/[id]/components/EventItemTotalSection.tsx
  apps/web/src/app/event/[category]/detail/[id]/page.tsx
  apps/web/src/app/event/[category]/layout.tsx
  apps/web/src/app/event/[category]/page.tsx
  apps/web/src/app/layout.tsx
  apps/web/src/app/main/[category]/EventItems.tsx
  apps/web/src/app/main/[category]/page.tsx
  apps/web/src/app/search/view/SearchResultView.tsx
  apps/web/src/components/EventItemCard/index.tsx
  apps/web/src/constants/conveniences.ts
  apps/web/src/hooks/query/usePromotion.ts
  yarn.lock
Labels: feature

#40 feat(web): 이벤트 리스트 페이지 빈 상품 ui
  apps/web/src/app/event/[category]/components/EventItems.tsx
  apps/web/src/hooks/query/usePromotion.ts
Labels: feature

#42 feat(web): 추천 콘텐츠 컨텐츠 스타일 수정
  apps/web/next.config.js
  apps/web/package.json
  apps/web/src/apis/recommendation.ts
  apps/web/src/app/hottrend/[category]/[id]/@info/loading.tsx
  apps/web/src/app/hottrend/[category]/[id]/@info/page.tsx
  apps/web/src/app/hottrend/[category]/[id]/@rank/loading.tsx
  apps/web/src/app/hottrend/[category]/[id]/@rank/page.tsx
  apps/web/src/app/hottrend/[category]/[id]/HotTrendInfo.tsx
  apps/web/src/app/hottrend/[category]/[id]/layout.tsx
  apps/web/src/app/hottrend/[category]/[id]/page.tsx
  apps/web/src/app/hottrend/[category]/route.ts
  apps/web/src/app/recommendation/contents/[id]/page.tsx
  apps/web/src/dummy/recommendation.ts
  yarn.lock
Labels: style

#43 feat(web): 검색 메인페이지 api연동
  apps/web/src/apis/recommendation.ts
  apps/web/src/app/main/Header.tsx
  apps/web/src/app/search/components/HotTrendSection.tsx
  apps/web/src/app/search/components/PerfectMatchSection.tsx
  apps/web/src/app/search/components/RecommendSection.tsx
  apps/web/src/app/search/components/RecommendSlides.tsx
  apps/web/src/app/search/view/SearchView.tsx
  apps/web/src/utils/getRandomFromArray.ts
Labels: feature

#44 feat(web): 검색 결과 페이지 api 작업
  apps/web/src/apis/promotion.ts
  apps/web/src/app/search/components/SearchResultList.tsx
  apps/web/src/app/search/view/SearchResultView.tsx
  apps/web/src/hooks/query/usePromotion.ts
Labels: feature
