Repository HAND-PYEON/handpyeon-web, pull requests merged in 2023-08, with the labels that each got.

#45 fix(web): 핫트렌드에서 새로고침 시 생기는 무한 요청 수정
  apps/web/src/app/hottrend/[category]/[id]/@info/(page)/page.tsx
Labels: bug, fix

#46 feat(web): 핫트렌드, 추천 콘텐츠 에러 및 로딩 컴포넌트 업데이트
  apps/web/public/icons/sorry.svg
  apps/web/src/app/hottrend/[category]/[id]/@info/error.tsx
  apps/web/src/app/hottrend/[category]/[id]/@info/loading.tsx
  apps/web/src/app/hottrend/[category]/[id]/@rank/error.tsx
  apps/web/src/app/hottrend/[category]/[id]/@rank/loading.tsx
  apps/web/src/app/hottrend/[category]/[id]/@rank/page.tsx
  apps/web/src/app/recommendation/[category]/error.tsx
  apps/web/src/app/recommendation/[category]/loading.tsx
  apps/web/src/app/recommendation/[category]/page.tsx
  apps/web/src/app/recommendation/contents/[id]/error.tsx
  apps/web/src/app/recommendation/contents/[id]/loading.tsx
  apps/web/src/app/recommendation/contents/[id]/page.tsx
  apps/web/src/components/ErrorSorry/index.tsx
  apps/web/src/components/icons/SorryIcon.tsx
  apps/web/src/hooks/query/useRecommendation.ts
Labels: feature

#47 docs: README.md 업데이트
  README.md
Labels: documentation

#48 style(web): 404에러페이지 작업
  apps/web/public/image/NotFound.png
  apps/web/src/app/not-found.tsx
  apps/web/src/components/HomeIconButton/index.tsx
  apps/web/src/components/NotFoundPage.tsx
Labels: bug, style, fix
